[package]
name = "Up_down_right_left_up"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.24"
libloading = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
